services:
  backend:
    container_name: backend
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    env_file:
      - .env
    command:
      uvicorn src.api.main:app --host 0.0.0.0 --port ${BACKEND_PORT} --reload
    restart: always
