services:
  backend:
    container_name: backend
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    env_file:
      - .env
    command:
      uvicorn src.api.main:app --host 0.0.0.0 --port ${BACKEND_PORT} --reload
    restart: always

  mongo:
    image: mongo:7-jammy
    container_name: mongo
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - mongo:/data/db
      - mongo-config:/data/configdb
    restart: always

  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - '8080:80'
  #   depends_on:
  #     - mongo
  #     - backend
  #   restart: always

volumes:
  mongo:
  mongo-config: